// POC only -- 1 hand-picked demo item, generated by Gemini (original content,
// not from any copyrighted book) with Gemini TTS audio. Not wired into the
// shared progress/Stats system yet; that comes once the real data pipeline
// (script transcription + storage strategy) is settled. See feature/listening
// branch discussion for the plan.
import listeningPocRaw from "../data/listening-poc.json";
import type { ListeningDataset, ListeningQuestion } from "../types/listening.ts";

const pocDataset = listeningPocRaw as unknown as ListeningDataset;

export const ALL_LISTENING: ListeningQuestion[] = [...pocDataset.questions];

const LISTENING_BY_ID = new Map(ALL_LISTENING.map((q) => [q.id, q]));
export function findListeningById(id: string): ListeningQuestion | undefined {
  return LISTENING_BY_ID.get(id);
}
